In [1]:
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()

In [4]:
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [89]:
X=iris['data']

In [6]:
y=iris['target']

In [8]:
y.dtype

dtype('int32')

In [9]:
from sklearn.cross_validation import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

In [15]:
import tensorflow.contrib.learn as learn

In [40]:
feature_columns = [tf.contrib.layers.real_valued_column("", dimension=4)]
classifier = learn.DNNClassifier(hidden_units=[10,20,10],n_classes=3,feature_columns=feature_columns)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_task_type': None, '_task_id': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000000000FAE3358>, '_master': '', '_num_ps_replicas': 0, '_num_worker_replicas': 0, '_environment': 'local', '_is_chief': True, '_evaluation_master': '', '_train_distribute': None, '_device_fn': None, '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1.0
}
, '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_secs': 600, '_log_step_count_steps': 100, '_session_config': None, '_save_checkpoints_steps': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_model_dir': 'C:\\Users\\winuser\\AppData\\Local\\Temp\\tmp6d0s3ktd'}


In [75]:
classifier.fit(X_train,y_train,steps=200,batch_size=30)

INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\winuser\AppData\Local\Temp\tmp6d0s3ktd\model.ckpt-700
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 700 into C:\Users\winuser\AppData\Local\Temp\tmp6d0s3ktd\model.ckpt.
INFO:tensorflow:loss = 0.10154473, step = 701
INFO:tensorflow:global_step/sec: 980.392
INFO:tensorflow:loss = 0.08255847, step = 801 (0.102 sec)
INFO:tensorflow:Saving checkpoints for 900 into C:\Users\winuser\AppData\Local\Temp\tmp6d0s3ktd\model.ckpt.
INFO:tensorflow:Loss for final step: 0.08053114.


DNNClassifier(params={'head': <tensorflow.contrib.learn.python.learn.estimators.head._MultiClassHead object at 0x000000000FAE3208>, 'hidden_units': [10, 20, 10], 'feature_columns': (_RealValuedColumn(column_name='', dimension=4, default_value=None, dtype=tf.float32, normalizer=None),), 'optimizer': None, 'activation_fn': <function relu at 0x000000000A0676A8>, 'dropout': None, 'gradient_clip_norm': None, 'embedding_lr_multipliers': None, 'input_layer_min_slice_size': None})

In [83]:
iris_predictions = classifier.predict(X_test)


INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\winuser\AppData\Local\Temp\tmp6d0s3ktd\model.ckpt-900
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [84]:
pred1 =list(iris_predictions)

print(pred1)

[0, 0, 2, 0, 1, 2, 2, 2, 0, 1, 0, 1, 0, 1, 1, 2, 2, 2, 0, 0, 2, 0, 2, 1, 2, 1, 0, 2, 0, 1, 0, 0, 1, 1, 2, 1, 1, 0, 1, 0, 2, 2, 0, 1, 2, 1, 0, 2, 1, 0]


In [67]:
from sklearn.metrics import classification_report,confusion_matrix

In [85]:
print(classification_report(y_test,pred1))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        18
          1       1.00      1.00      1.00        16
          2       1.00      1.00      1.00        16

avg / total       1.00      1.00      1.00        50



In [86]:
print(confusion_matrix(y_test,pred))

[[18  0  0]
 [ 0 16  0]
 [ 0  0 16]]
